### ISSUE TITLE
Update model code on HuggingFace

### ISSUE THREAD

**Issue by johnflavin** [microsoft/hi-ml#956] opened 2024-09-09 17:55 UTC
When running the `microsoft/BiomedVLP-CXR-BERT-specialized` model from HuggingFace, I get the following error:
```
Traceback (most recent call last):
  File "/app/app.py", line 96, in read_item
    vector = await vec.vectorize(item.text, item.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/vectorizer.py", line 50, in vectorize
    return await asyncio.wrap_future(self.executor.submit(self.vectorizer.vectorize, text, config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/vectorizer.py", line 165, in vectorize
    batch_results = self.get_batch_results(tokens, sentences[start_index:end_index])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/vectorizer.py", line 137, in get_batch_results
    return self.model_delegate.get_batch_results(tokens, text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/vectorizer.py", line 191, in get_batch_results
    return self.model(**tokens)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/BiomedVLP-CXR-BERT-specialized/b59c09e51ab2410b24f4be214bbb49043fe63fc2/modeling_cxrbert.py", line 98, in forward
    return CXRBertOutput(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/generic.py", line 355, in __init__
    raise TypeError(
TypeError: transformers_modules.microsoft.BiomedVLP-CXR-BERT-specialized.b59c09e51ab2410b24f4be214bbb49043fe63fc2.modeling_cxrbert.CXRBertOutput is not a dataclasss. This is a subclass of ModelOutput and so must use the @dataclass decorator.
```
This error has been fixed in this repo since #928, but those fixes have not been deployed to the HuggingFace model. Could you please deploy the updated code to the HuggingFace model? 

(And a slight side request, the model has a backlog of PRs from users trying to fix this issue: https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized/discussions?status=open&type=pull_request. Those could presumably be closed if/when the updated code gets deployed from this repo.)

**Comment by fepegar** [comment] 2024-09-09 18:22
Hi, @johnflavin. We solved this on Hugging Face today. Can you please try again?

**Comment by johnflavin** [comment] 2024-09-09 18:30
The files I can see on both [microsoft/BiomedVLP-CXR-BERT-general](https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-general/tree/main) and [microsoft/BiomedVLP-CXR-BERT-specialized](https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized/tree/main) (which is what I'm attempting to use) do not seem to have been updated in two years.

**Comment by fepegar** [comment] 2024-09-09 18:35
You're right! Apologies. We fixed the same error in https://huggingface.co/microsoft/BiomedVLP-BioViL-T. Would you like to contribute with a PR on HF?

**Comment by johnflavin** [comment] 2024-09-09 18:50
There is already a PR on `microsoft/BiomedVLP-CXR-BERT-specialized` that appears to update the `modeling_cxrbert.py` to be up-to-date with this repo: https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized/discussions/7. Could you (or someone with appropriate permissions) merge that one?

**Comment by KendallPark** [comment] 2024-09-09 21:21
@johnflavin until then, you can use my PR via:

```
kwargs['revision'] = '6cfc310817fb7d86762d888ced1e3709c57ac578'
model = AutoModel.from_pretrained('microsoft/BiomedVLP-CXR-BERT-specialized', trust_remote_code=True, **kwargs)
```

It is working as intended for me.

**Comment by fepegar** [comment] 2024-09-10 10:01
Fixed by @KendallPark in https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized/discussions/7. Thank you both for your contributions!

**Closed by fepegar** 2024-09-10 10:01 UTC
Labels: hi-ml-multimodal
